# Generated by Django 5.0 on 2025-12-04 15:15

import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="ActivityCategory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name_en", models.CharField(max_length=100)),
                ("name_hi", models.CharField(max_length=100)),
                ("description_en", models.TextField()),
                ("description_hi", models.TextField()),
                ("icon", models.CharField(max_length=50)),
                ("color", models.CharField(default="#FFB6C1", max_length=7)),
                ("display_order", models.IntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "Activity Categories",
                "db_table": "activity_categories",
                "ordering": ["display_order", "name_en"],
            },
        ),
        migrations.CreateModel(
            name="Badge",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name_en", models.CharField(max_length=100)),
                ("name_hi", models.CharField(max_length=100)),
                ("description_en", models.TextField()),
                ("description_hi", models.TextField()),
                ("icon", models.CharField(max_length=100)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("streak", "Streak"),
                            ("completion", "Completion"),
                            ("category", "Category"),
                            ("special", "Special"),
                            ("milestone", "Milestone"),
                        ],
                        max_length=20,
                    ),
                ),
                ("criteria", models.JSONField()),
                ("points_reward", models.IntegerField(default=50)),
                ("coins_reward", models.IntegerField(default=20)),
                (
                    "rarity",
                    models.CharField(
                        choices=[
                            ("common", "Common"),
                            ("rare", "Rare"),
                            ("epic", "Epic"),
                            ("legendary", "Legendary"),
                        ],
                        default="common",
                        max_length=10,
                    ),
                ),
                ("display_order", models.IntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "badges",
                "ordering": ["display_order", "name_en"],
            },
        ),
        migrations.CreateModel(
            name="Milestone",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name_en", models.CharField(max_length=100)),
                ("name_hi", models.CharField(max_length=100)),
                ("description_en", models.TextField()),
                ("description_hi", models.TextField()),
                ("icon", models.CharField(max_length=50)),
                (
                    "milestone_type",
                    models.CharField(
                        choices=[
                            ("relationship_duration", "Relationship Duration"),
                            ("activity_count", "Activity Count"),
                            ("streak", "Streak"),
                            ("special", "Special Event"),
                        ],
                        max_length=30,
                    ),
                ),
                ("criteria_value", models.IntegerField()),
                ("points_reward", models.IntegerField(default=100)),
                ("coins_reward", models.IntegerField(default=50)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "milestones",
            },
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        error_messages={
                            "unique": "A user with that username already exists."
                        },
                        help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                        max_length=150,
                        unique=True,
                        validators=[
                            django.contrib.auth.validators.UnicodeUsernameValidator()
                        ],
                        verbose_name="username",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                (
                    "google_id",
                    models.CharField(
                        blank=True, max_length=255, null=True, unique=True
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(blank=True, max_length=15, null=True),
                ),
                (
                    "age",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(13),
                            django.core.validators.MaxValueValidator(120),
                        ],
                    ),
                ),
                ("profile_picture", models.URLField(blank=True, null=True)),
                ("bio", models.TextField(blank=True, max_length=500, null=True)),
                ("relationship_start_date", models.DateField(blank=True, null=True)),
                (
                    "partner_invitation_code",
                    models.CharField(blank=True, max_length=8, null=True, unique=True),
                ),
                (
                    "preferred_language",
                    models.CharField(
                        choices=[("en", "English"), ("hi", "Hindi")],
                        default="en",
                        max_length=5,
                    ),
                ),
                (
                    "theme",
                    models.CharField(
                        choices=[
                            ("light", "Light"),
                            ("dark", "Dark"),
                            ("auto", "Auto"),
                        ],
                        default="auto",
                        max_length=10,
                    ),
                ),
                ("total_points", models.IntegerField(default=0)),
                ("current_level", models.IntegerField(default=1)),
                ("coins", models.IntegerField(default=0)),
                ("last_active", models.DateTimeField(auto_now=True)),
                ("is_online", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "partner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="partner_of",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "db_table": "users",
            },
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="Activity",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title_en", models.CharField(max_length=200)),
                ("title_hi", models.CharField(max_length=200)),
                ("description_en", models.TextField()),
                ("description_hi", models.TextField()),
                ("instructions_en", models.JSONField()),
                ("instructions_hi", models.JSONField()),
                (
                    "difficulty",
                    models.CharField(
                        choices=[
                            ("easy", "Easy"),
                            ("medium", "Medium"),
                            ("deep", "Deep"),
                        ],
                        default="medium",
                        max_length=10,
                    ),
                ),
                (
                    "estimated_time_minutes",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(5),
                            django.core.validators.MaxValueValidator(120),
                        ]
                    ),
                ),
                (
                    "best_time",
                    models.CharField(
                        choices=[
                            ("morning", "Morning"),
                            ("afternoon", "Afternoon"),
                            ("evening", "Evening"),
                            ("anytime", "Anytime"),
                        ],
                        default="anytime",
                        max_length=10,
                    ),
                ),
                (
                    "mode",
                    models.CharField(
                        choices=[
                            ("solo", "Solo"),
                            ("together", "Together"),
                            ("both", "Both"),
                        ],
                        default="both",
                        max_length=10,
                    ),
                ),
                ("materials_needed_en", models.JSONField(blank=True, null=True)),
                ("materials_needed_hi", models.JSONField(blank=True, null=True)),
                ("tips_en", models.JSONField(blank=True, null=True)),
                ("tips_hi", models.JSONField(blank=True, null=True)),
                ("questions_en", models.JSONField(blank=True, null=True)),
                ("questions_hi", models.JSONField(blank=True, null=True)),
                ("points_reward", models.IntegerField(default=10)),
                ("coins_reward", models.IntegerField(default=10)),
                ("is_premium", models.BooleanField(default=False)),
                ("unlock_cost_coins", models.IntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("is_daily_featured", models.BooleanField(default=False)),
                ("completion_count", models.IntegerField(default=0)),
                (
                    "average_rating",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=3),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activities",
                        to="bondingapp.activitycategory",
                    ),
                ),
            ],
            options={
                "db_table": "activities",
            },
        ),
        migrations.CreateModel(
            name="ActivitySession",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("started", "Started"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("skipped", "Skipped"),
                            ("abandoned", "Abandoned"),
                        ],
                        default="started",
                        max_length=20,
                    ),
                ),
                (
                    "mode",
                    models.CharField(
                        choices=[("solo", "Solo"), ("together", "Together")],
                        default="solo",
                        max_length=10,
                    ),
                ),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("time_spent_seconds", models.IntegerField(default=0)),
                (
                    "activity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sessions",
                        to="bondingapp.activity",
                    ),
                ),
                (
                    "partner_session",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="linked_session",
                        to="bondingapp.activitysession",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activity_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "activity_sessions",
            },
        ),
        migrations.CreateModel(
            name="ActivityCompletion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("responses", models.JSONField(blank=True, null=True)),
                ("photos", models.JSONField(blank=True, null=True)),
                ("notes", models.TextField(blank=True, null=True)),
                (
                    "rating",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                ("feedback", models.TextField(blank=True, null=True)),
                ("points_earned", models.IntegerField(default=10)),
                ("coins_earned", models.IntegerField(default=10)),
                ("shared_with_partner", models.BooleanField(default=True)),
                ("completed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "activity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="completions",
                        to="bondingapp.activity",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activity_completions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "session",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="completion",
                        to="bondingapp.activitysession",
                    ),
                ),
            ],
            options={
                "db_table": "activity_completions",
                "ordering": ["-completed_at"],
            },
        ),
        migrations.CreateModel(
            name="CoinTransaction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[
                            ("earned_activity", "Earned from Activity"),
                            ("earned_daily_bonus", "Daily Login Bonus"),
                            ("earned_streak", "Streak Bonus"),
                            ("earned_badge", "Badge Reward"),
                            ("earned_milestone", "Milestone Reward"),
                            ("spent_unlock", "Spent to Unlock"),
                            ("spent_hint", "Spent on Hint"),
                            ("spent_theme", "Spent on Theme"),
                            ("spent_custom", "Spent on Custom Activity"),
                        ],
                        max_length=30,
                    ),
                ),
                ("amount", models.IntegerField()),
                ("balance_after", models.IntegerField()),
                ("related_object_id", models.UUIDField(blank=True, null=True)),
                (
                    "related_object_type",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("description", models.CharField(max_length=200)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="coin_transactions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "coin_transactions",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("partner_activity", "Partner Activity"),
                            ("streak_reminder", "Streak Reminder"),
                            ("daily_activity", "Daily Activity"),
                            ("badge_unlocked", "Badge Unlocked"),
                            ("milestone_achieved", "Milestone Achieved"),
                            ("partner_invite", "Partner Invitation"),
                            ("partner_joined", "Partner Joined"),
                        ],
                        max_length=30,
                    ),
                ),
                ("title_en", models.CharField(max_length=200)),
                ("title_hi", models.CharField(max_length=200)),
                ("message_en", models.TextField()),
                ("message_hi", models.TextField()),
                ("data", models.JSONField(blank=True, null=True)),
                ("is_read", models.BooleanField(default=False)),
                ("is_sent", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("read_at", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "notifications",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SkipLimit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(default=django.utils.timezone.now)),
                ("skips_used", models.IntegerField(default=0)),
                ("max_skips_per_day", models.IntegerField(default=2)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="skip_limits",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "skip_limits",
            },
        ),
        migrations.CreateModel(
            name="Streak",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("current_streak", models.IntegerField(default=0)),
                ("longest_streak", models.IntegerField(default=0)),
                ("last_activity_date", models.DateField(blank=True, null=True)),
                ("total_active_days", models.IntegerField(default=0)),
                ("streak_start_date", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="streaks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "streaks",
                "ordering": ["-current_streak"],
            },
        ),
        migrations.CreateModel(
            name="UserBadge",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("unlocked_at", models.DateTimeField(auto_now_add=True)),
                ("is_displayed", models.BooleanField(default=False)),
                (
                    "badge",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_badges",
                        to="bondingapp.badge",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="unlocked_badges",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "user_badges",
                "ordering": ["-unlocked_at"],
            },
        ),
        migrations.CreateModel(
            name="UserMilestone",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("achieved_at", models.DateTimeField(auto_now_add=True)),
                ("partner_also_achieved", models.BooleanField(default=False)),
                (
                    "milestone",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_milestones",
                        to="bondingapp.milestone",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="achieved_milestones",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "user_milestones",
                "ordering": ["-achieved_at"],
            },
        ),
        migrations.CreateModel(
            name="UserPreference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("daily_reminder_enabled", models.BooleanField(default=True)),
                ("daily_reminder_time", models.TimeField(default="09:00:00")),
                ("partner_activity_alerts", models.BooleanField(default=True)),
                ("streak_reminders", models.BooleanField(default=True)),
                ("milestone_notifications", models.BooleanField(default=True)),
                ("sound_enabled", models.BooleanField(default=True)),
                ("vibration_enabled", models.BooleanField(default=True)),
                (
                    "activity_difficulty",
                    models.CharField(
                        choices=[
                            ("easy", "Easy"),
                            ("medium", "Medium"),
                            ("deep", "Deep"),
                            ("all", "All"),
                        ],
                        default="all",
                        max_length=10,
                    ),
                ),
                (
                    "notification_frequency",
                    models.CharField(
                        choices=[
                            ("high", "High"),
                            ("medium", "Medium"),
                            ("low", "Low"),
                        ],
                        default="medium",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="preferences",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "user_preferences",
            },
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(fields=["email"], name="users_email_4b85f2_idx"),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(fields=["google_id"], name="users_google__d35fe6_idx"),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(
                fields=["partner_invitation_code"], name="users_partner_c0fd23_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="activity",
            index=models.Index(
                fields=["category", "difficulty"], name="activities_categor_c8703c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="activity",
            index=models.Index(
                fields=["is_daily_featured"], name="activities_is_dail_a47bef_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="activity",
            index=models.Index(
                fields=["is_premium"], name="activities_is_prem_c01cda_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="activitysession",
            index=models.Index(
                fields=["user", "status"], name="activity_se_user_id_2b2078_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="activitysession",
            index=models.Index(
                fields=["started_at"], name="activity_se_started_7724a2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="activitycompletion",
            index=models.Index(
                fields=["user", "completed_at"], name="activity_co_user_id_f7fe76_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="activitycompletion",
            index=models.Index(
                fields=["activity"], name="activity_co_activit_18c09f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="cointransaction",
            index=models.Index(
                fields=["user", "created_at"], name="coin_transa_user_id_7a0565_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(
                fields=["user", "is_read"], name="notificatio_user_id_a4dd5c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(
                fields=["created_at"], name="notificatio_created_e4c995_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="skiplimit",
            unique_together={("user", "date")},
        ),
        migrations.AlterUniqueTogether(
            name="userbadge",
            unique_together={("user", "badge")},
        ),
        migrations.AlterUniqueTogether(
            name="usermilestone",
            unique_together={("user", "milestone")},
        ),
    ]
